spring:
    output:
        ansi:
            enabled: ALWAYS
    main:
        banner-mode: "OFF"
    data:
        web:
            pageable:
                one-indexed-parameters: true
                default-page-size: 20
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
        username: ${PGUSER}
        password: ${PGPASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
        database: postgresql
        database-platform: 
        show-sql: true
    jackson:
        date-format: yyyy-MM-dd
    flyway:
        # clean-on-validation-error: true
        enabled: true
        url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
        user: ${PGUSER}
        password: ${PGPASSWORD}
        locations: "classpath:db/migration"
        # schemas: public
        # baseline-on-migrate: true
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                trace: false
                web-allow-others: false
server:
    port: "${PORT:8080}"
    error:
        include-stacktrace: on-param
        include-message: always
        include-binding-errors: always
    
logging:
    level:
        ROOT: INFO
        org:
            flywaydb: DEBUG
        com:
            mkdata:
                company: INFO
mkdata:
  app:
    jwtSecret: "======================Mkdata=Spring==========================="
    jwtExpirationMs: 86400000