spring:
    output:
        ansi:
            enabled: ALWAYS
    main:
        banner-mode: "OFF"
    data:
        web:
            pageable:
                one-indexed-parameters: true
                default-page-size: 20
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
        username: ${PGUSER}
        password: ${PGPASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
        database: postgresql
        show-sql: true
    jackson:
        date-format: yyyy-MM-dd
    flyway:
        clean-on-validation-error: true
        enabled: true
        url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
        user: ${PGUSER}
        password: ${PGPASSWORD}
        locations: "classpath:db/migration"
        schemas: public
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                trace: false
                web-allow-others: false
springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-ui.html
        enabled: true
server:
    port: "${PORT:8080}"
    error:
        include-stacktrace: on-param
        include-message: always
        include-binding-errors: always
logging:
    level:
        ROOT: INFO
        com:
            mkdata:
                company: INFO
